import { HttpClient } from '@angular/common/http';
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { EmailService } from 'src/app/services/email.service';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  @Input() isDisabled: boolean = false;
  formularioReclamo!: FormGroup;
  formularios: any;

  files: File[] = [];
  maxSize: number = 10 * 1024 * 1024; // 10 MB en bytes
  errorMessage: string = '';
  isButtonDisabled: boolean = false;

  constructor(public fb: FormBuilder, private emailService: EmailService,
              ) { }

  localidades: any[] = [
    { localidad: 'AGUADA CECILIO', codigoPostal: '8534' },
    { localidad: 'AGUADA DE CORDOBA', codigoPostal: '8332' },
    { localidad: 'AGUADA DE GUANACO', codigoPostal: '8418' },
    { localidad: 'AGUADA DE GUERRA', codigoPostal: '8424' },
    { localidad: 'AGUADA DEL LORO', codigoPostal: '8520' },
    { localidad: 'AGUADA DE LOS PAJARITOS', codigoPostal: '8301' },
    { localidad: 'AGUADA DE PIEDRA', codigoPostal: '8422' },
    { localidad: 'AGUADA ESCONDIDA', codigoPostal: '8418' },
    { localidad: 'AGUADA GUZMAN', codigoPostal: '8333' },
    { localidad: 'AGUADA TRONCOSO (EMBARCADERO FCGR)', codigoPostal: '8415' },
    { localidad: 'AGUA DEL CERRO', codigoPostal: '8415' },
    { localidad: 'AGUARA', codigoPostal: '8307' },
    { localidad: 'ALANITOS', codigoPostal: '8333' },
    { localidad: 'ALEJANDRO STEFENELLI', codigoPostal: '8332' },
    { localidad: 'ALLEN', codigoPostal: '8328' },
    { localidad: 'ANECON CHICO', codigoPostal: '8418' },
    { localidad: 'ANECON GRANDE', codigoPostal: '8416' },
    { localidad: 'ANTIGUO GENERAL ROCA', codigoPostal: '8332' },
    { localidad: 'ARROYO BLANCO', codigoPostal: '8403' },
    { localidad: 'ARROYO CHACAY', codigoPostal: '8401' },
    { localidad: 'ARROYO DE LA VENTANA', codigoPostal: '8521' },
    { localidad: 'ARROYO LAS MINAS', codigoPostal: '8415' },
    { localidad: 'ARROYO LOS BERROS', codigoPostal: '8521' },
    { localidad: 'ARROYO MARTIN (ÑORQUINCO, DPTO. ÑORQUINCO)', codigoPostal: '8415' },
    { localidad: 'ARROYO MARTIN (MAQUINCHAO, DPTO. 25 DE MAYO)', codigoPostal: '8422' },
    { localidad: 'ARROYO SALADO', codigoPostal: '8532' },
    { localidad: 'ARROYO TEMBRADO', codigoPostal: '8521' },
    { localidad: 'ARROYO VERDE', codigoPostal: '8521' },
    { localidad: 'ATRAICO', codigoPostal: '8418' },
    { localidad: 'BAHIA LOPEZ', codigoPostal: '8400' },
    { localidad: 'BAJO PICASO', codigoPostal: '8536' },
    { localidad: 'BAJO RICO', codigoPostal: '8360' },
    { localidad: 'BALNEARIO EL CONDOR', codigoPostal: '8501' },
    { localidad: 'BALNEARIO LA BOCA', codigoPostal: '8501' },
    { localidad: 'BALNEARIO LAS GRUTAS', codigoPostal: '8521' },
    { localidad: 'BALNEARIO MASSINI', codigoPostal: '8500' },
    { localidad: 'BARDA COLORADA', codigoPostal: '8333' },
    { localidad: 'BARDA CHICA', codigoPostal: '8324' },
    { localidad: 'BARDA DEL MEDIO', codigoPostal: '8305' },
    { localidad: 'BARILOCHE', codigoPostal: '8400' },
    { localidad: 'BARRIL NIYEO', codigoPostal: '8422' },
    { localidad: 'BARRIO DON BOSCO', codigoPostal: '8336' },
    { localidad: 'BARRIO LAGUNA', codigoPostal: '8520' },
    { localidad: 'BARRIO LAS QUINTAS', codigoPostal: '8400' },
    { localidad: 'BARRIO MATADEROS', codigoPostal: '8336' },
    { localidad: 'BARRIO NIRECO', codigoPostal: '8400' },
    { localidad: 'BARRIO NORTE', codigoPostal: '8328' },
    { localidad: 'BARRIO TRESCIENTAS VIVIENDAS', codigoPostal: '8324' },
    { localidad: 'BENJAMIN ZORRILLA', codigoPostal: '8360' },
    { localidad: 'BLANCA CHICA', codigoPostal: '8422' },
    { localidad: 'BLANCA LOMA', codigoPostal: '8332' },
    { localidad: 'BOCA DE LA TRAVESIA', codigoPostal: '8505' },
    { localidad: 'BUENA PARADA', codigoPostal: '8138' },
    { localidad: 'BUENZANIYEU', codigoPostal: '8424' },
    { localidad: 'CAIN', codigoPostal: '8332' },
    { localidad: 'CALTRAUNA', codigoPostal: '8424' },
    { localidad: 'CAMPAMENTO', codigoPostal: '8332' },
    { localidad: 'CAÑADA GRANDE', codigoPostal: '8424' },
    { localidad: 'CAÑADON COMALLO', codigoPostal: '8416' },
    { localidad: 'CAÑADON CHILENO', codigoPostal: '8417' },
    { localidad: 'CAÑADON DEL CORRAL', codigoPostal: '8412' },
    { localidad: 'CAÑADON DE LOS SAUCES', codigoPostal: '8363' },
    { localidad: 'CAÑADON TRINCAO', codigoPostal: '8332' },
    { localidad: 'CARHUE', codigoPostal: '8412' },
    { localidad: 'CARRILAUQUEN', codigoPostal: '8418' },
    { localidad: 'CARRI YEGUA', codigoPostal: '8417' },
    { localidad: 'CASA QUEMADA', codigoPostal: '8412' },
    { localidad: 'CATRIEL', codigoPostal: '8307' },
    { localidad: 'CERRO ABANICO (APEADERO FCGR)', codigoPostal: '8424' },
    { localidad: 'CERRO ALTO', codigoPostal: '8403' },
    { localidad: 'CERRO BARAJA', codigoPostal: '8505' },
    { localidad: 'CERRO CATEDRAL', codigoPostal: '8401' },
    { localidad: 'CERRO DAVID', codigoPostal: '8412' },
    { localidad: 'CERRO DE LA POLICIA', codigoPostal: '8333' },
    { localidad: 'CERRO DE LOS VIEJOS', codigoPostal: '8138' },
    { localidad: 'CERRO DE POLICIA', codigoPostal: '8333' },
    { localidad: 'CERRO FRANCISCO', codigoPostal: '8505' },
    { localidad: 'CERRO GALENSE', codigoPostal: '8363' },
    { localidad: 'CERRO MESA', codigoPostal: '8415' },
    { localidad: 'CERVANTES', codigoPostal: '8326' },
    { localidad: 'CINCO CHAÑARES', codigoPostal: '8520' },
    { localidad: 'CINCO LAGUNAS', codigoPostal: '8138' },
    { localidad: 'CINCO SALTOS', codigoPostal: '8303' },
    { localidad: 'CIPOLLETTI', codigoPostal: '8324' },
    { localidad: 'CLEMENTE ONELLI', codigoPostal: '8416' },
    { localidad: 'COLINIYEN', codigoPostal: '8332' },
    { localidad: 'COLI TORO', codigoPostal: '8418' },
    { localidad: 'COLONIA ALMIRANTE GUERRICO', codigoPostal: '8307' },
    { localidad: 'COLONIA CATRIEL', codigoPostal: '8307' },
    { localidad: 'COLONIA CHILAVERT', codigoPostal: '8532' },
    { localidad: 'COLONIA EL MANZANO', codigoPostal: '8305' },
    { localidad: 'COLONIA GRAL. FRIAS', codigoPostal: '8501' },
    { localidad: 'COLONIA JOSEFA', codigoPostal: '8363' },
    { localidad: 'COLONIA JULIA y ECHARREN', codigoPostal: '8138' },
    { localidad: 'COLONIA LA LUISA', codigoPostal: '8503' },
    { localidad: 'COLONIA LOS CANALES', codigoPostal: '8316' },
    { localidad: 'COLONIA REGINA', codigoPostal: '8336' },
    { localidad: 'COLONIA RUSA', codigoPostal: '8332' },
    { localidad: 'COLONIA SAN JUAN', codigoPostal: '8503' },
    { localidad: 'COLONIA SUIZA', codigoPostal: '8400' },
    { localidad: 'COMALLO', codigoPostal: '8416' },
    { localidad: 'COMALLO ABAJO', codigoPostal: '8416' },
    { localidad: 'COMI-C', codigoPostal: '8424' },
    { localidad: 'CONA NIYEU', codigoPostal: '8521' },
    { localidad: 'CONTRALMIRANTE CORDERO', codigoPostal: '8301' },
    { localidad: 'CONTRALMIRANTE MARTIN GUERRICO', codigoPostal: '8328' },
    { localidad: 'COQUELEN', codigoPostal: '8416' },
    { localidad: 'CORONEL BELISLE', codigoPostal: '8364' },
    { localidad: 'CORONEL EUGENIO DEL BUSTO', codigoPostal: '8138' },
    { localidad: 'CORONEL FRANCISCO SOSA (EMBARCADRO FCGR)', codigoPostal: '8503' },
    { localidad: 'CORONEL JUAN JOSE GOMEZ', codigoPostal: '8333' },
    { localidad: 'CORONEL VIDAL', codigoPostal: '8305' },
    { localidad: 'CORRAL CHICO', codigoPostal: '8534' },
    { localidad: 'CORRAL DE LOS PINOS', codigoPostal: '8412' },
    { localidad: 'CORRALITO', codigoPostal: '8403' },
    { localidad: 'COSTA DEL RIO AZUL', codigoPostal: '8430' },
    { localidad: 'COSTAS DEL PICHI LEUFU', codigoPostal: '8412' },
    { localidad: 'COS ZAURES', codigoPostal: '8307' },
    { localidad: 'COYUE CO', codigoPostal: '8333' },
    { localidad: 'CUATRO ESQUINAS', codigoPostal: '8324' },
    { localidad: 'CUBANEA', codigoPostal: '8501' },
    { localidad: 'CUENCA VIDAL', codigoPostal: '8301' },
    { localidad: 'CURA LAUQUEN', codigoPostal: '8417' },
    { localidad: 'CUYEN-LEUFU', codigoPostal: '8534' },
    { localidad: 'CHACALHUA RUCA', codigoPostal: '8415' },
    { localidad: 'CHACAY HUARRUCA', codigoPostal: '8415' },
    { localidad: 'CHACOY (BRACA)', codigoPostal: '8415' },
    { localidad: 'CHACRAS DE ALLEN', codigoPostal: '8328' },
    { localidad: 'CHAIFUL', codigoPostal: '8418' },
    { localidad: 'CHASICO', codigoPostal: '8417' },
    { localidad: 'CHAUQUEN', codigoPostal: '8536' },
    { localidad: 'CHELFORO', codigoPostal: '8366' },
    { localidad: 'CHENQUENIYEU', codigoPostal: '8412' },
    { localidad: 'CHICHIHUAO', codigoPostal: '8422' },
    { localidad: 'CHICHINALES', codigoPostal: '8326' },
    { localidad: 'CHIMPAY', codigoPostal: '8364' },
    { localidad: 'CHINA MUERTA', codigoPostal: '8504' },
    { localidad: 'CHINQUENIYEU', codigoPostal: '8412' },
    { localidad: 'CHIPAUQUIL', codigoPostal: '8536' },
    { localidad: 'CHOCORI', codigoPostal: '8503' },
    { localidad: 'CHOELE CHOEL', codigoPostal: '8360' },
    { localidad: 'CHURQUIÑEO', codigoPostal: '8412' },
    { localidad: 'DARWIN', codigoPostal: '8364' },
    { localidad: 'DOCTOR ROGELIO CORTIZO (EMPALME)', codigoPostal: '8520' },
    { localidad: 'DON GUILLERMO', codigoPostal: '8418' },
    { localidad: 'EL AGUILA', codigoPostal: '8138' },
    { localidad: 'EL BOLSON', codigoPostal: '8430' },
    { localidad: 'EL CACIQUE', codigoPostal: '8417' },
    { localidad: 'EL CAIN', codigoPostal: '8422' },
    { localidad: 'EL CALDEN', codigoPostal: '8138' },
    { localidad: 'EL CAMARURO', codigoPostal: '8417' },
    { localidad: 'EL CUY', codigoPostal: '8333' },
    { localidad: 'EL CHEIFUL', codigoPostal: '8418' },
    { localidad: 'EL DIQUE', codigoPostal: '8500' },
    { localidad: 'EL FOYEL', codigoPostal: '8401' },
    { localidad: 'EL GAUCHO POBRE', codigoPostal: '8417' },
    { localidad: 'EL HINOJO', codigoPostal: '8364' },
    { localidad: 'EL JARDINERO', codigoPostal: '8417' },
    { localidad: 'EL MANSO', codigoPostal: '8430' },
    { localidad: 'EL MANZANO', codigoPostal: '8328' },
    { localidad: 'EL MIRADOR', codigoPostal: '8418' },
    { localidad: 'EL MOLIGUE', codigoPostal: '8418' },
    { localidad: 'EL MOLINO', codigoPostal: '8364' },
    { localidad: 'EL MONTOSO', codigoPostal: '8418' },
    { localidad: 'EL PANTANOSO', codigoPostal: '8412' },
    { localidad: 'EL SALADO', codigoPostal: '8536' },
    { localidad: 'EL TREBOL', codigoPostal: '8138' },
    { localidad: 'EMPALME DOCTOR ROGELIO CORTISO', codigoPostal: '8520' },
    { localidad: 'EMPALME KILOMETRO 648 (APEADERO FCGR)', codigoPostal: '8418' },
    { localidad: 'ESTANCIA EL CONDOR', codigoPostal: '8400' },
    { localidad: 'ESTANCIA LAS JULIAS', codigoPostal: '8363' },
    { localidad: 'FALCKNER', codigoPostal: '8534' },
    { localidad: 'FERRI', codigoPostal: '8301' },
    { localidad: 'FITALANCAO (EMBARCADERO FCGR)', codigoPostal: '8415' },
    { localidad: 'FITAMICHE', codigoPostal: '8415' },
    { localidad: 'FITATIMEN', codigoPostal: '8415' },
    { localidad: 'FORTIN UNO', codigoPostal: '8360' },
    { localidad: 'FUERTE GENERAL ROCA', codigoPostal: '8332' },
    { localidad: 'FUERTE RUIN (EMBARCADERO FCGR)', codigoPostal: '8418' },
    { localidad: 'GARZU LAUQUEN (APEADERO FCGR)', codigoPostal: '8424' },
    { localidad: 'GARRAS', codigoPostal: '8324' },
    { localidad: 'GENERAL CONESA', codigoPostal: '8503' },
    { localidad: 'GENERAL ENRIQUE GODOY', codigoPostal: '8336' },
    { localidad: 'GENERAL FERNANDEZ ORO', codigoPostal: '8324' },
    { localidad: 'GENERAL LIBORIO BERNAL', codigoPostal: '8500' },
    { localidad: 'GENERAL LORENZO VINTTER', codigoPostal: '8514' },
    { localidad: 'GENERAL NICOLAS H. PALACIOS', codigoPostal: '8514' },
    { localidad: 'GENERAL ROCA', codigoPostal: '8332' },
    { localidad: 'GUARDIA MITRE', codigoPostal: '8505' },
    { localidad: 'HOTEL BAHIA LOPEZ', codigoPostal: '8400' },
    { localidad: 'HOTEL EL TREBOL', codigoPostal: '8409' },
    { localidad: 'HOTEL ENTRE LAGOS', codigoPostal: '8409' },
    { localidad: 'HOTEL LOS COIHUES', codigoPostal: '8400' },
    { localidad: 'HUA-MICHE', codigoPostal: '8417' },
    { localidad: 'HUAN LUAN', codigoPostal: '8418' },
    { localidad: 'HURRACA (CHACAY)', codigoPostal: '8415' },
    { localidad: 'INGENIERO HUERGO', codigoPostal: '8334' },
    { localidad: 'INGENIERO JACOBACCI', codigoPostal: '8418' },
    { localidad: 'INGENIERO JULIAN ROMERO', codigoPostal: '8336' },
    { localidad: 'INGENIERO OTTO KRAUSE', codigoPostal: '8336' },
    { localidad: 'INGENIERO ZIMMERMANN RESTA (APEADERO FCGR)', codigoPostal: '8416' },
    { localidad: 'INGENIO SAN LORENZO', codigoPostal: '8503' },
    { localidad: 'ISLA CHICA', codigoPostal: '8363' },
    { localidad: 'ISLA GRANDE', codigoPostal: '8361' },
    { localidad: 'JAGUEL CAMPO MONTE', codigoPostal: '8520' },
    { localidad: 'JANINUE', codigoPostal: '8534' },
    { localidad: 'JITA RUSIA', codigoPostal: '8417' },
    { localidad: 'JONES', codigoPostal: '8506' },
    { localidad: 'JUAN DE GARAY', codigoPostal: '8138' },
    { localidad: 'KILI MALAL', codigoPostal: '8417' },
    { localidad: 'KILOMETRO 823', codigoPostal: '8134' },
    { localidad: 'KILOMETRO 1071', codigoPostal: '8336' },
    { localidad: 'KILOMETRO 1099', codigoPostal: '8336' },
    { localidad: 'KILOMETRO 1218', codigoPostal: '8305' },
    { localidad: 'LA ADELA', codigoPostal: '8138' },
    { localidad: 'LA ALIANZA', codigoPostal: '8324' },
    { localidad: 'LA AMISTAD', codigoPostal: '9138' },
    { localidad: 'LA ANGOSTURA', codigoPostal: '8417' },
    { localidad: 'LA BALSA', codigoPostal: '8332' },
    { localidad: 'LA BOMBILLA', codigoPostal: '8520' },
    { localidad: 'LA CAROLINA', codigoPostal: '8503' },
    { localidad: 'LA COSTA', codigoPostal: '8332' },
    { localidad: 'LA CRIOLLITA', codigoPostal: '8417' },
    { localidad: 'LA CHILENA', codigoPostal: '8417' },
    { localidad: 'LA ELVIRA', codigoPostal: '8360' },
    { localidad: 'LA EMILIA', codigoPostal: '8324' },
    { localidad: 'LA ESMERALDA (DARWIN, DPTO. AVELLANEDA)', codigoPostal: '8364' },
    { localidad: 'LA ESMERALDA (CIPOLLETTI, DPTO. GRAL. ROCA)', codigoPostal: '8324' },
    { localidad: 'LA ESPERANZA', codigoPostal: '8534' },
    { localidad: 'LA ESTANCIA VIEJA', codigoPostal: '8324' },
    { localidad: 'LA ESTRELLA', codigoPostal: '8417' },
    { localidad: 'LA EXCURRA', codigoPostal: '8417' },
    { localidad: 'LA FLECHA', codigoPostal: '8503' },
    { localidad: 'LA GEROMITA', codigoPostal: '8332' },
    { localidad: 'LAGO GUTIERREZ', codigoPostal: '8400' },
    { localidad: 'LAGO MASCARDI', codigoPostal: '8401' },
    { localidad: 'LAGO MORENO', codigoPostal: '8400' },
    { localidad: 'LAGO PELLEGRINI', codigoPostal: '8305' },
    { localidad: 'LA GRANJA', codigoPostal: '8501' },
    { localidad: 'LAGUNA BLANCA', codigoPostal: '8417' },
    { localidad: 'LAGUNA CORTES', codigoPostal: '8520' },
    { localidad: 'LAGUNA DE LA PRUEBA', codigoPostal: '8520' },
    { localidad: 'LAGUNA DEL BARRO', codigoPostal: '8514' },
    { localidad: 'LAGUNA DEL CHASICO', codigoPostal: '8138' },
    { localidad: 'LAGUNA DEL MONTE', codigoPostal: '8514' },
    { localidad: 'LAGUNA FRIAS', codigoPostal: '8411' },
    { localidad: 'LAGUNA GUANACO', codigoPostal: '8422' },
    { localidad: 'LAGUNITA', codigoPostal: '8424' },
    { localidad: 'LA JUANITA (DARWIN, DPTO. AVELLANEDA)', codigoPostal: '8364' },
    { localidad: 'LA JUANITA (RIO COLORADO, DPTO. PICHI MAHUIDA)', codigoPostal: '8138' },
    { localidad: 'LA JULIA', codigoPostal: '8363' },
    { localidad: 'LA LUCINDA', codigoPostal: '8324' },
    { localidad: 'LA LUNA', codigoPostal: '8138' },
    { localidad: 'LA MARIA INES', codigoPostal: '8138' },
    { localidad: 'LAMARQUE', codigoPostal: '8363' },
    { localidad: 'LA MESETA', codigoPostal: '8500' },
    { localidad: 'LA MIMOSA', codigoPostal: '8417' },
    { localidad: 'LA MONTAÑESA', codigoPostal: '8138' },
    { localidad: 'LANQUIÑEO', codigoPostal: '8417' },
    { localidad: 'LA PAMPA', codigoPostal: '8138' },
    { localidad: 'LA PICASA', codigoPostal: '8303' },
    { localidad: 'LA PORTEÑA', codigoPostal: '8417' },
    { localidad: 'LA PRIMAVERA', codigoPostal: '8520' },
    { localidad: 'LA QUEBRADA', codigoPostal: '8412' },
    { localidad: 'LA RINCONADA', codigoPostal: '8424' },
    { localidad: 'LA RUBIA', codigoPostal: '8417' },
    { localidad: 'LA SARA', codigoPostal: '8360' },
    { localidad: 'LAS BAYAS', codigoPostal: '8412' },
    { localidad: 'LAS GRUTAS', codigoPostal: '8520' },
    { localidad: 'LA SIN BOMBO', codigoPostal: '8336' },
    { localidad: 'LAS MAQUINAS', codigoPostal: '8520' },
    { localidad: 'LAS MELLIZAS', codigoPostal: '8417' },
    { localidad: 'LAS MOCHAS', codigoPostal: '8534' },
    { localidad: 'LAS ÑATITAS', codigoPostal: '8324' },
    { localidad: 'LA TEODOLINA', codigoPostal: '8366' },
    { localidad: 'LA VENCEDORA', codigoPostal: '8417' },
    { localidad: 'LANZANIYEN', codigoPostal: '8424' },
    { localidad: 'LIPETREN', codigoPostal: '8534' },
    { localidad: 'LOMA BLANCA', codigoPostal: '8424' },
    { localidad: 'LOMA PARTIDA', codigoPostal: '8418' },
    { localidad: 'LOS CANTAROS', codigoPostal: '8411' },
    { localidad: 'LOS COSTEROS', codigoPostal: '8417' },
    { localidad: 'LOS JUNCOS (DPTO. PILCANIYEU)', codigoPostal: '8400' },
    { localidad: 'LOS JUNCOS (APEADERO FCGR) (MAQUINCHAO, DPTO. 25 DE MAYO)', codigoPostal: '8422' },
    { localidad: 'LOS MANANTIALES', codigoPostal: '8422' },
    { localidad: 'LOS MENUCOS (DPTO. 25 DE MAYO)', codigoPostal: '8424' },
    { localidad: 'LOS MOLINOS', codigoPostal: '8360' },
    { localidad: 'LOS PIRINEOS', codigoPostal: '8417' },
    { localidad: 'LOS QUEBRACHOS', codigoPostal: '8417' },
    { localidad: 'LOS REPOLLOS', codigoPostal: '8430' },
    { localidad: 'LOS SAUCES', codigoPostal: '8307' },
    { localidad: 'LUIS BELTRAN', codigoPostal: '8361' },
    { localidad: 'LUIS M. ZAGAGLIA', codigoPostal: '8503' },
    { localidad: 'LUPAY NIYEO', codigoPostal: '8332' },
    { localidad: 'LLAO LLAO', codigoPostal: '8409' },
    { localidad: 'MACACHIN', codigoPostal: '8536' },
    { localidad: 'MAINQUE', codigoPostal: '8326' },
    { localidad: 'MALLIN AHOGADO', codigoPostal: '8430' },
    { localidad: 'MAMUEL CHOIQUE', codigoPostal: '8415' },
    { localidad: 'MANCULLIQUE', codigoPostal: '8422' },
    { localidad: 'MANCHA BLANCA', codigoPostal: '8520' },
    { localidad: 'MAQUINCHAO', codigoPostal: '8422' },
    { localidad: 'MARI LAUQUEN', codigoPostal: '8422' },
    { localidad: 'MATA NEGRA', codigoPostal: '8500' },
    { localidad: 'MEDIA LUNA', codigoPostal: '8332' },
    { localidad: 'MENCUE', codigoPostal: '8417' },
    { localidad: 'MENUCO NEGRO', codigoPostal: '8534' },
    { localidad: 'MENUCO VACA MUERTA', codigoPostal: '8412' },
    { localidad: 'MICHI HONOCA', codigoPostal: '8333' },
    { localidad: 'MICHIHUAO', codigoPostal: '8417' },
    { localidad: 'MINISTRO RAMOS MEXIA', codigoPostal: '8534' },
    { localidad: 'MIRA PAMPA', codigoPostal: '8366' },
    { localidad: 'MONTE BAGUAL', codigoPostal: '8501' },
    { localidad: 'MONTE REDONDO', codigoPostal: '8138' },
    { localidad: 'MULANILLO', codigoPostal: '8417' },
    { localidad: 'MUSTERS', codigoPostal: '8536' },
    { localidad: 'NAHUEL NIYEU', codigoPostal: '8536' },
    { localidad: 'NAUPA HUEN', codigoPostal: '8313' },
    { localidad: 'NEGRO MUERTO', codigoPostal: '8360' },
    { localidad: 'NENEO RUCA (ESTACION FCGR)', codigoPostal: '8416' },
    { localidad: 'NILUAN', codigoPostal: '8422' },
    { localidad: 'NIRIHUAO (ESTACION FCGR)', codigoPostal: '8400' },
    { localidad: 'NITRALA MACOHUE', codigoPostal: '8418' },
    { localidad: 'NUEVA CAROLINA', codigoPostal: '8503' },
    { localidad: 'NUEVO LEON', codigoPostal: '8514' },
    { localidad: 'ÑIRIHUAO', codigoPostal: '8400' },
    { localidad: 'ÑORQUINCO', codigoPostal: '8415' },
    { localidad: 'OJOS DE AGUA (LLAO LLAO, DPTO. BARILOCHE)', codigoPostal: '8409' },
    { localidad: 'OJOS DE AGUA (EMBARC. FCGR, ING. JACOBACCI, DPTO.25 DE MAYO)', codigoPostal: '8418' },
    { localidad: 'PADRE ALEJANDRO STEFENELLI', codigoPostal: '8332' },
    { localidad: 'PAJALTA (APEADERO FCGR)', codigoPostal: '8536' },
    { localidad: 'PALENQUE NIYEU', codigoPostal: '8417' },
    { localidad: 'PANQUEHUAO', codigoPostal: '8412' },
    { localidad: 'PASO CORDOVA', codigoPostal: '8333' },
    { localidad: 'PASO CHACABUCO', codigoPostal: '8401' },
    { localidad: 'PASO DEL LIMAY', codigoPostal: '8403' },
    { localidad: 'PASO DE LOS MOLLES', codigoPostal: '8412' },
    { localidad: 'PASO FLORES', codigoPostal: '8403' },
    { localidad: 'PASO LEZCANO', codigoPostal: '8361' },
    { localidad: 'PASO MIRANDA', codigoPostal: '8403' },
    { localidad: 'PASO PEÑALVA', codigoPostal: '8363' },
    { localidad: 'PASO PIEDRA', codigoPostal: '8360' },
    { localidad: 'PATU CO', codigoPostal: '8333' },
    { localidad: 'PENINSULA HUEMUL', codigoPostal: '8400' },
    { localidad: 'PENINSULA SAN PEDRO', codigoPostal: '8401' },
    { localidad: 'PEÑAS BLANCAS', codigoPostal: '8307' },
    { localidad: 'PERCY H. SCOTT (APEADERO FCGR)', codigoPostal: '8520' },
    { localidad: 'PERITO MORENO', codigoPostal: '8416' },
    { localidad: 'PICHI LEUFU (APEADERO FCGR)', codigoPostal: '8412' },
    { localidad: 'PICHI LEUFU ABAJO', codigoPostal: '8412' },
    { localidad: 'PICHI LEUFU ARRIBA', codigoPostal: '8412' },
    { localidad: 'PICHI MAHUIDA', codigoPostal: '8138' },
    { localidad: 'PIEDRA BLANCA (SAN CARLOS DE BARILOCHE, DPTO. BARILOCHE)', codigoPostal: '8400' },
    { localidad: 'PIEDRA BLANCA (GRAL. ROCA, DPTO. GRAL. ROCA)', codigoPostal: '8332' },
    { localidad: 'PIEDRA CLAVADA', codigoPostal: '8536' },
    { localidad: 'PILAHUE', codigoPostal: '8417' },
    { localidad: 'PILCANIYEU', codigoPostal: '8412' },
    { localidad: 'PILCANIYEU VIEJO', codigoPostal: '8412' },
    { localidad: 'PLANICIE DE JAGUELITO', codigoPostal: '8333' },
    { localidad: 'PLAYA BONITA', codigoPostal: '8400' },
    { localidad: 'POMONA', codigoPostal: '8363' },
    { localidad: 'PORTEZUELO', codigoPostal: '8415' },
    { localidad: 'POZO MORO', codigoPostal: '8520' },
    { localidad: 'POZO SALADO', codigoPostal: '8514' },
    { localidad: 'PRAHUANIYEU', codigoPostal: '8424' },
    { localidad: 'PRIMERA ANGOSTURA', codigoPostal: '8505' },
    { localidad: 'PRONUNCIAMIENTO', codigoPostal: '8505' },
    { localidad: 'PUEBLO VIEJO', codigoPostal: '8332' },
    { localidad: 'PUERTO BLEST', codigoPostal: '8411' },
    { localidad: 'PUERTO HERMOSO', codigoPostal: '8422' },
    { localidad: 'PUERTO MORENO', codigoPostal: '8400' },
    { localidad: 'PUERTO OJO DE AGUA', codigoPostal: '8401' },
    { localidad: 'PUERTO PAÑUELO', codigoPostal: '8409' },
    { localidad: 'PUERTO PICHI MAHUIDA', codigoPostal: '8400' },
    { localidad: 'PUERTO SANTA MARIA', codigoPostal: '8401' },
    { localidad: 'PUERTO TIGRE', codigoPostal: '8400' },
    { localidad: 'PUESTO FARIA', codigoPostal: '8360' },
    { localidad: 'PUESTO GAVIÑA', codigoPostal: '8503' },
    { localidad: 'PUNTA DE AGUA', codigoPostal: '8356' },
    { localidad: 'QUEMPU NIYEU', codigoPostal: '8332' },
    { localidad: 'QUETREQUILE', codigoPostal: '8418' },
    { localidad: 'QUINIÑAU', codigoPostal: '8415' },
    { localidad: 'QUINTA PANAL', codigoPostal: '8416' },
    { localidad: 'QUO VADIS', codigoPostal: '8422' },
    { localidad: 'RAYHUAO', codigoPostal: '8412' },
    { localidad: 'REPOLLOS', codigoPostal: '8415' },
    { localidad: 'RINCONADA', codigoPostal: '8360' },
    { localidad: 'RINCON DE GASTRE', codigoPostal: '8503' },
    { localidad: 'RIO COLORADO', codigoPostal: '8138' },
    { localidad: 'RIO CHICO', codigoPostal: '8415' },
    { localidad: 'RIO NIRIHUANO', codigoPostal: '8400' },
    { localidad: 'RIO VILLEGAS', codigoPostal: '8401' },
    { localidad: 'RIVADAVIA', codigoPostal: '8418' },
    { localidad: 'RUCU LUAN', codigoPostal: '8422' },
    { localidad: 'RUTA 3 KILOMETRO 974', codigoPostal: '8500' },
    { localidad: 'SACO VIEJO', codigoPostal: '8514' },
    { localidad: 'SALITRAL NEGRO', codigoPostal: '8363' },
    { localidad: 'SAN ANTONIO DEL CUY', codigoPostal: '8333' },
    { localidad: 'SAN ANTONIO OESTE', codigoPostal: '8520' },
    { localidad: 'SAN CARLOS DE BARILOCHE', codigoPostal: '8400' },
    { localidad: 'SAN CAYETANO', codigoPostal: '8138' },
    { localidad: 'SAN EDUARDO', codigoPostal: '8332' },
    { localidad: 'SAN JAVIER', codigoPostal: '8501' },
    { localidad: 'SAN JORGE', codigoPostal: '8324' },
    { localidad: 'SAN JOSE DE PAJA ALTA', codigoPostal: '8536' },
    { localidad: 'SAN JUAN (GRAL. CONESA, DPTO. CONESA)', codigoPostal: '8503' },
    { localidad: 'SAN JUAN (RIO COLORADO, DPTO. PICHI MAHUIDA)', codigoPostal: '8138' },
    { localidad: 'SAN LEON', codigoPostal: '8138' },
    { localidad: 'SAN LORENZO', codigoPostal: '8503' },
    { localidad: 'SAN PABLO', codigoPostal: '8364' },
    { localidad: 'SAN PEDRO (RIO COLORADO, DPTO. PICHI MAHUIDA)', codigoPostal: '8138' },
    { localidad: 'SAN PEDRO (PILCANIYEU, DPTO. PILCANIYEU)', codigoPostal: '8412' },
    { localidad: 'SAN RAMON', codigoPostal: '8416' },
    { localidad: 'SAN SIMON', codigoPostal: '8503' },
    { localidad: 'SANTA ANA', codigoPostal: '8138' },
    { localidad: 'SANTA ELENA', codigoPostal: '8417' },
    { localidad: 'SANTA GENOVEVA', codigoPostal: '8363' },
    { localidad: 'SANTA GREGORIA', codigoPostal: '8364' },
    { localidad: 'SANTA JULIA', codigoPostal: '8366' },
    { localidad: 'SANTA NICOLASA', codigoPostal: '8364' },
    { localidad: 'SAUCE BLANCO (GUARDIA MITRE, DPTO. ADOLFO ALSINA)', codigoPostal: '8505' },
    { localidad: 'SAUCE BLANCO (CHOELE CHOEL, DPTO. AVELLANEDA)', codigoPostal: '8360' },
    { localidad: 'SEGUNDA ANGOSTURA', codigoPostal: '8501' },
    { localidad: 'SIERRA BLANCA', codigoPostal: '8534' },
    { localidad: 'SIERRA COLORADA', codigoPostal: '8534' },
    { localidad: 'SIERRA DE LA VENTANA', codigoPostal: '8521' },
    { localidad: 'SIERRA GRANDE', codigoPostal: '8532' },
    { localidad: 'SIERRA PAILEMAN', codigoPostal: '8521' },
    { localidad: 'TALCAHUALA (APEADERO FCGR)', codigoPostal: '8534' },
    { localidad: 'TAPILUQUE', codigoPostal: '8534' },
    { localidad: 'TENIENTE GRAL. EUSTAQUIO FRIAS', codigoPostal: '8501' },
    { localidad: 'TENIENTE MAZA (ESTACION FCGR)', codigoPostal: '8534' },
    { localidad: 'TERCERA ZONA', codigoPostal: '8336' },
    { localidad: 'TRAGUA TRAGUA', codigoPostal: '8360' },
    { localidad: 'TRAVESIA CASTRO', codigoPostal: '8503' },
    { localidad: 'TRECA-CO', codigoPostal: '8333' },
    { localidad: 'TRENETA', codigoPostal: '8534' },
    { localidad: 'TRES OJOS DE AGUA', codigoPostal: '8416' },
    { localidad: 'TRICACO', codigoPostal: '8332' },
    { localidad: 'TROMENIYEU', codigoPostal: '8422' },
    { localidad: 'TUNKELEN', codigoPostal: '8409' },
    { localidad: 'VACA LAUQUEN', codigoPostal: '8422' },
    { localidad: 'VALCHETA', codigoPostal: '8536' },
    { localidad: 'VALLE AZUL', codigoPostal: '8336' },
    { localidad: 'VALLE DE LOS ALAMOS', codigoPostal: '8307' },
    { localidad: 'VICEALMIRANTE EDUARDO O’CONNOR (ESTACION FCGR)', codigoPostal: '8514' },
    { localidad: 'VIEDMA', codigoPostal: '8500' },
    { localidad: 'VILLA ALBERDI', codigoPostal: '8336' },
    { localidad: 'VILLA LLANQUIN', codigoPostal: '8401' },
    { localidad: 'VILLA MASCARDI', codigoPostal: '8401' },
    { localidad: 'VILLA REGINA', codigoPostal: '8336' },
    { localidad: 'VILLA TURISMO', codigoPostal: '8430' },
    { localidad: 'YUQUINCHE', codigoPostal: '8418' },
    { localidad: 'ZANJON DE OYUELA', codigoPostal: '8501' },

  ];
  localidadesAlternativas2:any[] = [
    { localidad2: 'AGUADA CECILIO', codigoPostal2: '8534' },
    { localidad2: 'AGUADA DE CORDOBA', codigoPostal2: '8332' },
    { localidad2: 'AGUADA DE GUANACO', codigoPostal2: '8418' },
    { localidad2: 'AGUADA DE GUERRA', codigoPostal2: '8424' },
    { localidad2: 'AGUADA DEL LORO', codigoPostal2: '8520' },
    { localidad2: 'AGUADA DE LOS PAJARITOS', codigoPostal2: '8301' },
    { localidad2: 'AGUADA DE PIEDRA', codigoPostal2: '8422' },
    { localidad2: 'AGUADA ESCONDIDA', codigoPostal2: '8418' },
    { localidad2: 'AGUADA GUZMAN', codigoPostal2: '8333' },
    { localidad2: 'AGUADA TRONCOSO (EMBARCADERO FCGR)', codigoPostal2: '8415' },
    { localidad2: 'AGUA DEL CERRO', codigoPostal2: '8415' },
    { localidad2: 'AGUARA', codigoPostal2: '8307' },
    { localidad2: 'ALANITOS', codigoPostal2: '8333' },
    { localidad2: 'ALEJANDRO STEFENELLI', codigoPostal2: '8332' },
    { localidad2: 'ALLEN', codigoPostal2: '8328' },
    { localidad2: 'ANECON CHICO', codigoPostal2: '8418' },
    { localidad2: 'ANECON GRANDE', codigoPostal2: '8416' },
    { localidad2: 'ANTIGUO GENERAL ROCA', codigoPostal2: '8332' },
    { localidad2: 'ARROYO BLANCO', codigoPostal2: '8403' },
    { localidad2: 'ARROYO CHACAY', codigoPostal2: '8401' },
    { localidad2: 'ARROYO DE LA VENTANA', codigoPostal2: '8521' },
    { localidad2: 'ARROYO LAS MINAS', codigoPostal2: '8415' },
    { localidad2: 'ARROYO LOS BERROS', codigoPostal2: '8521' },
    { localidad2: 'ARROYO MARTIN (ÑORQUINCO, DPTO. ÑORQUINCO)', codigoPostal2: '8415' },
    { localidad2: 'ARROYO MARTIN (MAQUINCHAO, DPTO. 25 DE MAYO)', codigoPostal2: '8422' },
    { localidad2: 'ARROYO SALADO', codigoPostal2: '8532' },
    { localidad2: 'ARROYO TEMBRADO', codigoPostal2: '8521' },
    { localidad2: 'ARROYO VERDE', codigoPostal2: '8521' },
    { localidad2: 'ATRAICO', codigoPostal2: '8418' },
    { localidad2: 'BAHIA LOPEZ', codigoPostal2: '8400' },
    { localidad2: 'BAJO PICASO', codigoPostal2: '8536' },
    { localidad2: 'BAJO RICO', codigoPostal2: '8360' },
    { localidad2: 'BALNEARIO EL CONDOR', codigoPostal2: '8501' },
    { localidad2: 'BALNEARIO LA BOCA', codigoPostal2: '8501' },
    { localidad2: 'BALNEARIO LAS GRUTAS', codigoPostal2: '8521' },
    { localidad2: 'BALNEARIO MASSINI', codigoPostal2: '8500' },
    { localidad2: 'BARDA COLORADA', codigoPostal2: '8333' },
    { localidad2: 'BARDA CHICA', codigoPostal2: '8324' },
    { localidad2: 'BARDA DEL MEDIO', codigoPostal2: '8305' },
    { localidad2: 'BARILOCHE', codigoPostal2: '8400' },
    { localidad2: 'BARRIL NIYEO', codigoPostal2: '8422' },
    { localidad2: 'BARRIO DON BOSCO', codigoPostal2: '8336' },
    { localidad2: 'BARRIO LAGUNA', codigoPostal2: '8520' },
    { localidad2: 'BARRIO LAS QUINTAS', codigoPostal2: '8400' },
    { localidad2: 'BARRIO MATADEROS', codigoPostal2: '8336' },
    { localidad2: 'BARRIO NIRECO', codigoPostal2: '8400' },
    { localidad2: 'BARRIO NORTE', codigoPostal2: '8328' },
    { localidad2: 'BARRIO TRESCIENTAS VIVIENDAS', codigoPostal2: '8324' },
    { localidad2: 'BENJAMIN ZORRILLA', codigoPostal2: '8360' },
    { localidad2: 'BLANCA CHICA', codigoPostal2: '8422' },
    { localidad2: 'BLANCA LOMA', codigoPostal2: '8332' },
    { localidad2: 'BOCA DE LA TRAVESIA', codigoPostal2: '8505' },
    { localidad2: 'BUENA PARADA', codigoPostal2: '8138' },
    { localidad2: 'BUENZANIYEU', codigoPostal2: '8424' },
    { localidad2: 'CAIN', codigoPostal2: '8332' },
    { localidad2: 'CALTRAUNA', codigoPostal2: '8424' },
    { localidad2: 'CAMPAMENTO', codigoPostal2: '8332' },
    { localidad2: 'CAÑADA GRANDE', codigoPostal2: '8424' },
    { localidad2: 'CAÑADON COMALLO', codigoPostal2: '8416' },
    { localidad2: 'CAÑADON CHILENO', codigoPostal2: '8417' },
    { localidad2: 'CAÑADON DEL CORRAL', codigoPostal2: '8412' },
    { localidad2: 'CAÑADON DE LOS SAUCES', codigoPostal2: '8363' },
    { localidad2: 'CAÑADON TRINCAO', codigoPostal2: '8332' },
    { localidad2: 'CARHUE', codigoPostal2: '8412' },
    { localidad2: 'CARRILAUQUEN', codigoPostal2: '8418' },
    { localidad2: 'CARRI YEGUA', codigoPostal2: '8417' },
    { localidad2: 'CASA QUEMADA', codigoPostal2: '8412' },
    { localidad2: 'CATRIEL', codigoPostal2: '8307' },
    { localidad2: 'CERRO ABANICO (APEADERO FCGR)', codigoPostal2: '8424' },
    { localidad2: 'CERRO ALTO', codigoPostal2: '8403' },
    { localidad2: 'CERRO BARAJA', codigoPostal2: '8505' },
    { localidad2: 'CERRO CATEDRAL', codigoPostal2: '8401' },
    { localidad2: 'CERRO DAVID', codigoPostal2: '8412' },
    { localidad2: 'CERRO DE LA POLICIA', codigoPostal2: '8333' },
    { localidad2: 'CERRO DE LOS VIEJOS', codigoPostal2: '8138' },
    { localidad2: 'CERRO DE POLICIA', codigoPostal2: '8333' },
    { localidad2: 'CERRO FRANCISCO', codigoPostal2: '8505' },
    { localidad2: 'CERRO GALENSE', codigoPostal2: '8363' },
    { localidad2: 'CERRO MESA', codigoPostal2: '8415' },
    { localidad2: 'CERVANTES', codigoPostal2: '8326' },
    { localidad2: 'CINCO CHAÑARES', codigoPostal2: '8520' },
    { localidad2: 'CINCO LAGUNAS', codigoPostal2: '8138' },
    { localidad2: 'CINCO SALTOS', codigoPostal2: '8303' },
    { localidad2: 'CIPOLLETTI', codigoPostal2: '8324' },
    { localidad2: 'CLEMENTE ONELLI', codigoPostal2: '8416' },
    { localidad2: 'COLINIYEN', codigoPostal2: '8332' },
    { localidad2: 'COLI TORO', codigoPostal2: '8418' },
    { localidad2: 'COLONIA ALMIRANTE GUERRICO', codigoPostal2: '8307' },
    { localidad2: 'COLONIA CATRIEL', codigoPostal2: '8307' },
    { localidad2: 'COLONIA CHILAVERT', codigoPostal2: '8532' },
    { localidad2: 'COLONIA EL MANZANO', codigoPostal2: '8305' },
    { localidad2: 'COLONIA GRAL. FRIAS', codigoPostal2: '8501' },
    { localidad2: 'COLONIA JOSEFA', codigoPostal2: '8363' },
    { localidad2: 'COLONIA JULIA y ECHARREN', codigoPostal2: '8138' },
    { localidad2: 'COLONIA LA LUISA', codigoPostal2: '8503' },
    { localidad2: 'COLONIA LOS CANALES', codigoPostal2: '8316' },
    { localidad2: 'COLONIA REGINA', codigoPostal2: '8336' },
    { localidad2: 'COLONIA RUSA', codigoPostal2: '8332' },
    { localidad2: 'COLONIA SAN JUAN', codigoPostal2: '8503' },
    { localidad2: 'COLONIA SUIZA', codigoPostal2: '8400' },
    { localidad2: 'COMALLO', codigoPostal2: '8416' },
    { localidad2: 'COMALLO ABAJO', codigoPostal2: '8416' },
    { localidad2: 'COMI-C', codigoPostal2: '8424' },
    { localidad2: 'CONA NIYEU', codigoPostal2: '8521' },
    { localidad2: 'CONTRALMIRANTE CORDERO', codigoPostal2: '8301' },
    { localidad2: 'CONTRALMIRANTE MARTIN GUERRICO', codigoPostal2: '8328' },
    { localidad2: 'COQUELEN', codigoPostal2: '8416' },
    { localidad2: 'CORONEL BELISLE', codigoPostal2: '8364' },
    { localidad2: 'CORONEL EUGENIO DEL BUSTO', codigoPostal2: '8138' },
    { localidad2: 'CORONEL FRANCISCO SOSA (EMBARCADRO FCGR)', codigoPostal2: '8503' },
    { localidad2: 'CORONEL JUAN JOSE GOMEZ', codigoPostal2: '8333' },
    { localidad2: 'CORONEL VIDAL', codigoPostal2: '8305' },
    { localidad2: 'CORRAL CHICO', codigoPostal2: '8534' },
    { localidad2: 'CORRAL DE LOS PINOS', codigoPostal2: '8412' },
    { localidad2: 'CORRALITO', codigoPostal2: '8403' },
    { localidad2: 'COSTA DEL RIO AZUL', codigoPostal2: '8430' },
    { localidad2: 'COSTAS DEL PICHI LEUFU', codigoPostal2: '8412' },
    { localidad2: 'COS ZAURES', codigoPostal2: '8307' },
    { localidad2: 'COYUE CO', codigoPostal2: '8333' },
    { localidad2: 'CUATRO ESQUINAS', codigoPostal2: '8324' },
    { localidad2: 'CUBANEA', codigoPostal2: '8501' },
    { localidad2: 'CUENCA VIDAL', codigoPostal2: '8301' },
    { localidad2: 'CURA LAUQUEN', codigoPostal2: '8417' },
    { localidad2: 'CUYEN-LEUFU', codigoPostal2: '8534' },
    { localidad2: 'CHACALHUA RUCA', codigoPostal2: '8415' },
    { localidad2: 'CHACAY HUARRUCA', codigoPostal2: '8415' },
    { localidad2: 'CHACOY (BRACA)', codigoPostal2: '8415' },
    { localidad2: 'CHACRAS DE ALLEN', codigoPostal2: '8328' },
    { localidad2: 'CHAIFUL', codigoPostal2: '8418' },
    { localidad2: 'CHASICO', codigoPostal2: '8417' },
    { localidad2: 'CHAUQUEN', codigoPostal2: '8536' },
    { localidad2: 'CHELFORO', codigoPostal2: '8366' },
    { localidad2: 'CHENQUENIYEU', codigoPostal2: '8412' },
    { localidad2: 'CHICHIHUAO', codigoPostal2: '8422' },
    { localidad2: 'CHICHINALES', codigoPostal2: '8326' },
    { localidad2: 'CHIMPAY', codigoPostal2: '8364' },
    { localidad2: 'CHINA MUERTA', codigoPostal2: '8504' },
    { localidad2: 'CHINQUENIYEU', codigoPostal2: '8412' },
    { localidad2: 'CHIPAUQUIL', codigoPostal2: '8536' },
    { localidad2: 'CHOCORI', codigoPostal2: '8503' },
    { localidad2: 'CHOELE CHOEL', codigoPostal2: '8360' },
    { localidad2: 'CHURQUIÑEO', codigoPostal2: '8412' },
    { localidad2: 'DARWIN', codigoPostal2: '8364' },
    { localidad2: 'DOCTOR ROGELIO CORTIZO (EMPALME)', codigoPostal2: '8520' },
    { localidad2: 'DON GUILLERMO', codigoPostal2: '8418' },
    { localidad2: 'EL AGUILA', codigoPostal2: '8138' },
    { localidad2: 'EL BOLSON', codigoPostal2: '8430' },
    { localidad2: 'EL CACIQUE', codigoPostal2: '8417' },
    { localidad2: 'EL CAIN', codigoPostal2: '8422' },
    { localidad2: 'EL CALDEN', codigoPostal2: '8138' },
    { localidad2: 'EL CAMARURO', codigoPostal2: '8417' },
    { localidad2: 'EL CUY', codigoPostal2: '8333' },
    { localidad2: 'EL CHEIFUL', codigoPostal2: '8418' },
    { localidad2: 'EL DIQUE', codigoPostal2: '8500' },
    { localidad2: 'EL FOYEL', codigoPostal2: '8401' },
    { localidad2: 'EL GAUCHO POBRE', codigoPostal2: '8417' },
    { localidad2: 'EL HINOJO', codigoPostal2: '8364' },
    { localidad2: 'EL JARDINERO', codigoPostal2: '8417' },
    { localidad2: 'EL MANSO', codigoPostal2: '8430' },
    { localidad2: 'EL MANZANO', codigoPostal2: '8328' },
    { localidad2: 'EL MIRADOR', codigoPostal2: '8418' },
    { localidad2: 'EL MOLIGUE', codigoPostal2: '8418' },
    { localidad2: 'EL MOLINO', codigoPostal2: '8364' },
    { localidad2: 'EL MONTOSO', codigoPostal2: '8418' },
    { localidad2: 'EL PANTANOSO', codigoPostal2: '8412' },
    { localidad2: 'EL SALADO', codigoPostal2: '8536' },
    { localidad2: 'EL TREBOL', codigoPostal2: '8138' },
    { localidad2: 'EMPALME DOCTOR ROGELIO CORTISO', codigoPostal2: '8520' },
    { localidad2: 'EMPALME KILOMETRO 648 (APEADERO FCGR)', codigoPostal2: '8418' },
    { localidad2: 'ESTANCIA EL CONDOR', codigoPostal2: '8400' },
    { localidad2: 'ESTANCIA LAS JULIAS', codigoPostal2: '8363' },
    { localidad2: 'FALCKNER', codigoPostal2: '8534' },
    { localidad2: 'FERRI', codigoPostal2: '8301' },
    { localidad2: 'FITALANCAO (EMBARCADERO FCGR)', codigoPostal2: '8415' },
    { localidad2: 'FITAMICHE', codigoPostal2: '8415' },
    { localidad2: 'FITATIMEN', codigoPostal2: '8415' },
    { localidad2: 'FORTIN UNO', codigoPostal2: '8360' },
    { localidad2: 'FUERTE GENERAL ROCA', codigoPostal2: '8332' },
    { localidad2: 'FUERTE RUIN (EMBARCADERO FCGR)', codigoPostal2: '8418' },
    { localidad2: 'GARZU LAUQUEN (APEADERO FCGR)', codigoPostal2: '8424' },
    { localidad2: 'GARRAS', codigoPostal2: '8324' },
    { localidad2: 'GENERAL CONESA', codigoPostal2: '8503' },
    { localidad2: 'GENERAL ENRIQUE GODOY', codigoPostal2: '8336' },
    { localidad2: 'GENERAL FERNANDEZ ORO', codigoPostal2: '8324' },
    { localidad2: 'GENERAL LIBORIO BERNAL', codigoPostal2: '8500' },
    { localidad2: 'GENERAL LORENZO VINTTER', codigoPostal2: '8514' },
    { localidad2: 'GENERAL NICOLAS H. PALACIOS', codigoPostal2: '8514' },
    { localidad2: 'GENERAL ROCA', codigoPostal2: '8332' },
    { localidad2: 'GUARDIA MITRE', codigoPostal2: '8505' },
    { localidad2: 'HOTEL BAHIA LOPEZ', codigoPostal2: '8400' },
    { localidad2: 'HOTEL EL TREBOL', codigoPostal2: '8409' },
    { localidad2: 'HOTEL ENTRE LAGOS', codigoPostal2: '8409' },
    { localidad2: 'HOTEL LOS COIHUES', codigoPostal2: '8400' },
    { localidad2: 'HUA-MICHE', codigoPostal2: '8417' },
    { localidad2: 'HUAN LUAN', codigoPostal2: '8418' },
    { localidad2: 'HURRACA (CHACAY)', codigoPostal2: '8415' },
    { localidad2: 'INGENIERO HUERGO', codigoPostal2: '8334' },
    { localidad2: 'INGENIERO JACOBACCI', codigoPostal2: '8418' },
    { localidad2: 'INGENIERO JULIAN ROMERO', codigoPostal2: '8336' },
    { localidad2: 'INGENIERO OTTO KRAUSE', codigoPostal2: '8336' },
    { localidad2: 'INGENIERO ZIMMERMANN RESTA (APEADERO FCGR)', codigoPostal2: '8416' },
    { localidad2: 'INGENIO SAN LORENZO', codigoPostal2: '8503' },
    { localidad2: 'ISLA CHICA', codigoPostal2: '8363' },
    { localidad2: 'ISLA GRANDE', codigoPostal2: '8361' },
    { localidad2: 'JAGUEL CAMPO MONTE', codigoPostal2: '8520' },
    { localidad2: 'JANINUE', codigoPostal2: '8534' },
    { localidad2: 'JITA RUSIA', codigoPostal2: '8417' },
    { localidad2: 'JONES', codigoPostal2: '8506' },
    { localidad2: 'JUAN DE GARAY', codigoPostal2: '8138' },
    { localidad2: 'KILI MALAL', codigoPostal2: '8417' },
    { localidad2: 'KILOMETRO 823', codigoPostal2: '8134' },
    { localidad2: 'KILOMETRO 1071', codigoPostal2: '8336' },
    { localidad2: 'KILOMETRO 1099', codigoPostal2: '8336' },
    { localidad2: 'KILOMETRO 1218', codigoPostal2: '8305' },
    { localidad2: 'LA ADELA', codigoPostal2: '8138' },
    { localidad2: 'LA ALIANZA', codigoPostal2: '8324' },
    { localidad2: 'LA AMISTAD', codigoPostal2: '9138' },
    { localidad2: 'LA ANGOSTURA', codigoPostal2: '8417' },
    { localidad2: 'LA BALSA', codigoPostal2: '8332' },
    { localidad2: 'LA BOMBILLA', codigoPostal2: '8520' },
    { localidad2: 'LA CAROLINA', codigoPostal2: '8503' },
    { localidad2: 'LA COSTA', codigoPostal2: '8332' },
    { localidad2: 'LA CRIOLLITA', codigoPostal2: '8417' },
    { localidad2: 'LA CHILENA', codigoPostal2: '8417' },
    { localidad2: 'LA ELVIRA', codigoPostal2: '8360' },
    { localidad2: 'LA EMILIA', codigoPostal2: '8324' },
    { localidad2: 'LA ESMERALDA (DARWIN, DPTO. AVELLANEDA)', codigoPostal2: '8364' },
    { localidad2: 'LA ESMERALDA (CIPOLLETTI, DPTO. GRAL. ROCA)', codigoPostal2: '8324' },
    { localidad2: 'LA ESPERANZA', codigoPostal2: '8534' },
    { localidad2: 'LA ESTANCIA VIEJA', codigoPostal2: '8324' },
    { localidad2: 'LA ESTRELLA', codigoPostal2: '8417' },
    { localidad2: 'LA EXCURRA', codigoPostal2: '8417' },
    { localidad2: 'LA FLECHA', codigoPostal2: '8503' },
    { localidad2: 'LA GEROMITA', codigoPostal2: '8332' },
    { localidad2: 'LAGO GUTIERREZ', codigoPostal2: '8400' },
    { localidad2: 'LAGO MASCARDI', codigoPostal2: '8401' },
    { localidad2: 'LAGO MORENO', codigoPostal2: '8400' },
    { localidad2: 'LAGO PELLEGRINI', codigoPostal2: '8305' },
    { localidad2: 'LA GRANJA', codigoPostal2: '8501' },
    { localidad2: 'LAGUNA BLANCA', codigoPostal2: '8417' },
    { localidad2: 'LAGUNA CORTES', codigoPostal2: '8520' },
    { localidad2: 'LAGUNA DE LA PRUEBA', codigoPostal2: '8520' },
    { localidad2: 'LAGUNA DEL BARRO', codigoPostal2: '8514' },
    { localidad2: 'LAGUNA DEL CHASICO', codigoPostal2: '8138' },
    { localidad2: 'LAGUNA DEL MONTE', codigoPostal2: '8514' },
    { localidad2: 'LAGUNA FRIAS', codigoPostal2: '8411' },
    { localidad2: 'LAGUNA GUANACO', codigoPostal2: '8422' },
    { localidad2: 'LAGUNITA', codigoPostal2: '8424' },
    { localidad2: 'LA JUANITA (DARWIN, DPTO. AVELLANEDA)', codigoPostal2: '8364' },
    { localidad2: 'LA JUANITA (RIO COLORADO, DPTO. PICHI MAHUIDA)', codigoPostal2: '8138' },
    { localidad2: 'LA JULIA', codigoPostal2: '8363' },
    { localidad2: 'LA LUCINDA', codigoPostal2: '8324' },
    { localidad2: 'LA LUNA', codigoPostal2: '8138' },
    { localidad2: 'LA MARIA INES', codigoPostal2: '8138' },
    { localidad2: 'LAMARQUE', codigoPostal2: '8363' },
    { localidad2: 'LA MESETA', codigoPostal2: '8500' },
    { localidad2: 'LA MIMOSA', codigoPostal2: '8417' },
    { localidad2: 'LA MONTAÑESA', codigoPostal2: '8138' },
    { localidad2: 'LANQUIÑEO', codigoPostal2: '8417' },
    { localidad2: 'LA PAMPA', codigoPostal2: '8138' },
    { localidad2: 'LA PICASA', codigoPostal2: '8303' },
    { localidad2: 'LA PORTEÑA', codigoPostal2: '8417' },
    { localidad2: 'LA PRIMAVERA', codigoPostal2: '8520' },
    { localidad2: 'LA QUEBRADA', codigoPostal2: '8412' },
    { localidad2: 'LA RINCONADA', codigoPostal2: '8424' },
    { localidad2: 'LA RUBIA', codigoPostal2: '8417' },
    { localidad2: 'LA SARA', codigoPostal2: '8360' },
    { localidad2: 'LAS BAYAS', codigoPostal2: '8412' },
    { localidad2: 'LAS GRUTAS', codigoPostal2: '8520' },
    { localidad2: 'LA SIN BOMBO', codigoPostal2: '8336' },
    { localidad2: 'LAS MAQUINAS', codigoPostal2: '8520' },
    { localidad2: 'LAS MELLIZAS', codigoPostal2: '8417' },
    { localidad2: 'LAS MOCHAS', codigoPostal2: '8534' },
    { localidad2: 'LAS ÑATITAS', codigoPostal2: '8324' },
    { localidad2: 'LA TEODOLINA', codigoPostal2: '8366' },
    { localidad2: 'LA VENCEDORA', codigoPostal2: '8417' },
    { localidad2: 'LANZANIYEN', codigoPostal2: '8424' },
    { localidad2: 'LIPETREN', codigoPostal2: '8534' },
    { localidad2: 'LOMA BLANCA', codigoPostal2: '8424' },
    { localidad2: 'LOMA PARTIDA', codigoPostal2: '8418' },
    { localidad2: 'LOS CANTAROS', codigoPostal2: '8411' },
    { localidad2: 'LOS COSTEROS', codigoPostal2: '8417' },
    { localidad2: 'LOS JUNCOS (DPTO. PILCANIYEU)', codigoPostal2: '8400' },
    { localidad2: 'LOS JUNCOS (APEADERO FCGR) (MAQUINCHAO, DPTO. 25 DE MAYO)', codigoPostal2: '8422' },
    { localidad2: 'LOS MANANTIALES', codigoPostal2: '8422' },
    { localidad2: 'LOS MENUCOS (DPTO. 25 DE MAYO)', codigoPostal2: '8424' },
    { localidad2: 'LOS MOLINOS', codigoPostal2: '8360' },
    { localidad2: 'LOS PIRINEOS', codigoPostal2: '8417' },
    { localidad2: 'LOS QUEBRACHOS', codigoPostal2: '8417' },
    { localidad2: 'LOS REPOLLOS', codigoPostal2: '8430' },
    { localidad2: 'LOS SAUCES', codigoPostal2: '8307' },
    { localidad2: 'LUIS BELTRAN', codigoPostal2: '8361' },
    { localidad2: 'LUIS M. ZAGAGLIA', codigoPostal2: '8503' },
    { localidad2: 'LUPAY NIYEO', codigoPostal2: '8332' },
    { localidad2: 'LLAO LLAO', codigoPostal2: '8409' },
    { localidad2: 'MACACHIN', codigoPostal2: '8536' },
    { localidad2: 'MAINQUE', codigoPostal2: '8326' },
    { localidad2: 'MALLIN AHOGADO', codigoPostal2: '8430' },
    { localidad2: 'MAMUEL CHOIQUE', codigoPostal2: '8415' },
    { localidad2: 'MANCULLIQUE', codigoPostal2: '8422' },
    { localidad2: 'MANCHA BLANCA', codigoPostal2: '8520' },
    { localidad2: 'MAQUINCHAO', codigoPostal2: '8422' },
    { localidad2: 'MARI LAUQUEN', codigoPostal2: '8422' },
    { localidad2: 'MATA NEGRA', codigoPostal2: '8500' },
    { localidad2: 'MEDIA LUNA', codigoPostal2: '8332' },
    { localidad2: 'MENCUE', codigoPostal2: '8417' },
    { localidad2: 'MENUCO NEGRO', codigoPostal2: '8534' },
    { localidad2: 'MENUCO VACA MUERTA', codigoPostal2: '8412' },
    { localidad2: 'MICHI HONOCA', codigoPostal2: '8333' },
    { localidad2: 'MICHIHUAO', codigoPostal2: '8417' },
    { localidad2: 'MINISTRO RAMOS MEXIA', codigoPostal2: '8534' },
    { localidad2: 'MIRA PAMPA', codigoPostal2: '8366' },
    { localidad2: 'MONTE BAGUAL', codigoPostal2: '8501' },
    { localidad2: 'MONTE REDONDO', codigoPostal2: '8138' },
    { localidad2: 'MULANILLO', codigoPostal2: '8417' },
    { localidad2: 'MUSTERS', codigoPostal2: '8536' },
    { localidad2: 'NAHUEL NIYEU', codigoPostal2: '8536' },
    { localidad2: 'NAUPA HUEN', codigoPostal2: '8313' },
    { localidad2: 'NEGRO MUERTO', codigoPostal2: '8360' },
    { localidad2: 'NENEO RUCA (ESTACION FCGR)', codigoPostal2: '8416' },
    { localidad2: 'NILUAN', codigoPostal2: '8422' },
    { localidad2: 'NIRIHUAO (ESTACION FCGR)', codigoPostal2: '8400' },
    { localidad2: 'NITRALA MACOHUE', codigoPostal2: '8418' },
    { localidad2: 'NUEVA CAROLINA', codigoPostal2: '8503' },
    { localidad2: 'NUEVO LEON', codigoPostal2: '8514' },
    { localidad2: 'ÑIRIHUAO', codigoPostal2: '8400' },
    { localidad2: 'ÑORQUINCO', codigoPostal2: '8415' },
    { localidad2: 'OJOS DE AGUA (LLAO LLAO, DPTO. BARILOCHE)', codigoPostal2: '8409' },
    { localidad2: 'OJOS DE AGUA (EMBARC. FCGR, ING. JACOBACCI, DPTO.25 DE MAYO)', codigoPostal2: '8418' },
    { localidad2: 'PADRE ALEJANDRO STEFENELLI', codigoPostal2: '8332' },
    { localidad2: 'PAJALTA (APEADERO FCGR)', codigoPostal2: '8536' },
    { localidad2: 'PALENQUE NIYEU', codigoPostal2: '8417' },
    { localidad2: 'PANQUEHUAO', codigoPostal2: '8412' },
    { localidad2: 'PASO CORDOVA', codigoPostal2: '8333' },
    { localidad2: 'PASO CHACABUCO', codigoPostal2: '8401' },
    { localidad2: 'PASO DEL LIMAY', codigoPostal2: '8403' },
    { localidad2: 'PASO DE LOS MOLLES', codigoPostal2: '8412' },
    { localidad2: 'PASO FLORES', codigoPostal2: '8403' },
    { localidad2: 'PASO LEZCANO', codigoPostal2: '8361' },
    { localidad2: 'PASO MIRANDA', codigoPostal2: '8403' },
    { localidad2: 'PASO PEÑALVA', codigoPostal2: '8363' },
    { localidad2: 'PASO PIEDRA', codigoPostal2: '8360' },
    { localidad2: 'PATU CO', codigoPostal2: '8333' },
    { localidad2: 'PENINSULA HUEMUL', codigoPostal2: '8400' },
    { localidad2: 'PENINSULA SAN PEDRO', codigoPostal2: '8401' },
    { localidad2: 'PEÑAS BLANCAS', codigoPostal2: '8307' },
    { localidad2: 'PERCY H. SCOTT (APEADERO FCGR)', codigoPostal2: '8520' },
    { localidad2: 'PERITO MORENO', codigoPostal2: '8416' },
    { localidad2: 'PICHI LEUFU (APEADERO FCGR)', codigoPostal2: '8412' },
    { localidad2: 'PICHI LEUFU ABAJO', codigoPostal2: '8412' },
    { localidad2: 'PICHI LEUFU ARRIBA', codigoPostal2: '8412' },
    { localidad2: 'PICHI MAHUIDA', codigoPostal2: '8138' },
    { localidad2: 'PIEDRA BLANCA (SAN CARLOS DE BARILOCHE, DPTO. BARILOCHE)', codigoPostal2: '8400' },
    { localidad2: 'PIEDRA BLANCA (GRAL. ROCA, DPTO. GRAL. ROCA)', codigoPostal2: '8332' },
    { localidad2: 'PIEDRA CLAVADA', codigoPostal2: '8536' },
    { localidad2: 'PILAHUE', codigoPostal2: '8417' },
    { localidad2: 'PILCANIYEU', codigoPostal2: '8412' },
    { localidad2: 'PILCANIYEU VIEJO', codigoPostal2: '8412' },
    { localidad2: 'PLANICIE DE JAGUELITO', codigoPostal2: '8333' },
    { localidad2: 'PLAYA BONITA', codigoPostal2: '8400' },
    { localidad2: 'POMONA', codigoPostal2: '8363' },
    { localidad2: 'PORTEZUELO', codigoPostal2: '8415' },
    { localidad2: 'POZO MORO', codigoPostal2: '8520' },
    { localidad2: 'POZO SALADO', codigoPostal2: '8514' },
    { localidad2: 'PRAHUANIYEU', codigoPostal2: '8424' },
    { localidad2: 'PRIMERA ANGOSTURA', codigoPostal2: '8505' },
    { localidad2: 'PRONUNCIAMIENTO', codigoPostal2: '8505' },
    { localidad2: 'PUEBLO VIEJO', codigoPostal2: '8332' },
    { localidad2: 'PUERTO BLEST', codigoPostal2: '8411' },
    { localidad2: 'PUERTO HERMOSO', codigoPostal2: '8422' },
    { localidad2: 'PUERTO MORENO', codigoPostal2: '8400' },
    { localidad2: 'PUERTO OJO DE AGUA', codigoPostal2: '8401' },
    { localidad2: 'PUERTO PAÑUELO', codigoPostal2: '8409' },
    { localidad2: 'PUERTO PICHI MAHUIDA', codigoPostal2: '8400' },
    { localidad2: 'PUERTO SANTA MARIA', codigoPostal2: '8401' },
    { localidad2: 'PUERTO TIGRE', codigoPostal2: '8400' },
    { localidad2: 'PUESTO FARIA', codigoPostal2: '8360' },
    { localidad2: 'PUESTO GAVIÑA', codigoPostal2: '8503' },
    { localidad2: 'PUNTA DE AGUA', codigoPostal2: '8356' },
    { localidad2: 'QUEMPU NIYEU', codigoPostal2: '8332' },
    { localidad2: 'QUETREQUILE', codigoPostal2: '8418' },
    { localidad2: 'QUINIÑAU', codigoPostal2: '8415' },
    { localidad2: 'QUINTA PANAL', codigoPostal2: '8416' },
    { localidad2: 'QUO VADIS', codigoPostal2: '8422' },
    { localidad2: 'RAYHUAO', codigoPostal2: '8412' },
    { localidad2: 'REPOLLOS', codigoPostal2: '8415' },
    { localidad2: 'RINCONADA', codigoPostal2: '8360' },
    { localidad2: 'RINCON DE GASTRE', codigoPostal2: '8503' },
    { localidad2: 'RIO COLORADO', codigoPostal2: '8138' },
    { localidad2: 'RIO CHICO', codigoPostal2: '8415' },
    { localidad2: 'RIO NIRIHUANO', codigoPostal2: '8400' },
    { localidad2: 'RIO VILLEGAS', codigoPostal2: '8401' },
    { localidad2: 'RIVADAVIA', codigoPostal2: '8418' },
    { localidad2: 'RUCU LUAN', codigoPostal2: '8422' },
    { localidad2: 'RUTA 3 KILOMETRO 974', codigoPostal2: '8500' },
    { localidad2: 'SACO VIEJO', codigoPostal2: '8514' },
    { localidad2: 'SALITRAL NEGRO', codigoPostal2: '8363' },
    { localidad2: 'SAN ANTONIO DEL CUY', codigoPostal2: '8333' },
    { localidad2: 'SAN ANTONIO OESTE', codigoPostal2: '8520' },
    { localidad2: 'SAN CARLOS DE BARILOCHE', codigoPostal2: '8400' },
    { localidad2: 'SAN CAYETANO', codigoPostal2: '8138' },
    { localidad2: 'SAN EDUARDO', codigoPostal2: '8332' },
    { localidad2: 'SAN JAVIER', codigoPostal2: '8501' },
    { localidad2: 'SAN JORGE', codigoPostal2: '8324' },
    { localidad2: 'SAN JOSE DE PAJA ALTA', codigoPostal2: '8536' },
    { localidad2: 'SAN JUAN (GRAL. CONESA, DPTO. CONESA)', codigoPostal2: '8503' },
    { localidad2: 'SAN JUAN (RIO COLORADO, DPTO. PICHI MAHUIDA)', codigoPostal2: '8138' },
    { localidad2: 'SAN LEON', codigoPostal2: '8138' },
    { localidad2: 'SAN LORENZO', codigoPostal2: '8503' },
    { localidad2: 'SAN PABLO', codigoPostal2: '8364' },
    { localidad2: 'SAN PEDRO (RIO COLORADO, DPTO. PICHI MAHUIDA)', codigoPostal2: '8138' },
    { localidad2: 'SAN PEDRO (PILCANIYEU, DPTO. PILCANIYEU)', codigoPostal2: '8412' },
    { localidad2: 'SAN RAMON', codigoPostal2: '8416' },
    { localidad2: 'SAN SIMON', codigoPostal2: '8503' },
    { localidad2: 'SANTA ANA', codigoPostal2: '8138' },
    { localidad2: 'SANTA ELENA', codigoPostal2: '8417' },
    { localidad2: 'SANTA GENOVEVA', codigoPostal2: '8363' },
    { localidad2: 'SANTA GREGORIA', codigoPostal2: '8364' },
    { localidad2: 'SANTA JULIA', codigoPostal2: '8366' },
    { localidad2: 'SANTA NICOLASA', codigoPostal2: '8364' },
    { localidad2: 'SAUCE BLANCO (GUARDIA MITRE, DPTO. ADOLFO ALSINA)', codigoPostal2: '8505' },
    { localidad2: 'SAUCE BLANCO (CHOELE CHOEL, DPTO. AVELLANEDA)', codigoPostal2: '8360' },
    { localidad2: 'SEGUNDA ANGOSTURA', codigoPostal2: '8501' },
    { localidad2: 'SIERRA BLANCA', codigoPostal2: '8534' },
    { localidad2: 'SIERRA COLORADA', codigoPostal2: '8534' },
    { localidad2: 'SIERRA DE LA VENTANA', codigoPostal2: '8521' },
    { localidad2: 'SIERRA GRANDE', codigoPostal2: '8532' },
    { localidad2: 'SIERRA PAILEMAN', codigoPostal2: '8521' },
    { localidad2: 'TALCAHUALA (APEADERO FCGR)', codigoPostal2: '8534' },
    { localidad2: 'TAPILUQUE', codigoPostal2: '8534' },
    { localidad2: 'TENIENTE GRAL. EUSTAQUIO FRIAS', codigoPostal2: '8501' },
    { localidad2: 'TENIENTE MAZA (ESTACION FCGR)', codigoPostal2: '8534' },
    { localidad2: 'TERCERA ZONA', codigoPostal2: '8336' },
    { localidad2: 'TRAGUA TRAGUA', codigoPostal2: '8360' },
    { localidad2: 'TRAVESIA CASTRO', codigoPostal2: '8503' },
    { localidad2: 'TRECA-CO', codigoPostal2: '8333' },
    { localidad2: 'TRENETA', codigoPostal2: '8534' },
    { localidad2: 'TRES OJOS DE AGUA', codigoPostal2: '8416' },
    { localidad2: 'TRICACO', codigoPostal2: '8332' },
    { localidad2: 'TROMENIYEU', codigoPostal2: '8422' },
    { localidad2: 'TUNKELEN', codigoPostal2: '8409' },
    { localidad2: 'VACA LAUQUEN', codigoPostal2: '8422' },
    { localidad2: 'VALCHETA', codigoPostal2: '8536' },
    { localidad2: 'VALLE AZUL', codigoPostal2: '8336' },
    { localidad2: 'VALLE DE LOS ALAMOS', codigoPostal2: '8307' },
    { localidad2: 'VICEALMIRANTE EDUARDO O’CONNOR (ESTACION FCGR)', codigoPostal2: '8514' },
    { localidad2: 'VIEDMA', codigoPostal2: '8500' },
    { localidad2: 'VILLA ALBERDI', codigoPostal2: '8336' },
    { localidad2: 'VILLA LLANQUIN', codigoPostal2: '8401' },
    { localidad2: 'VILLA MASCARDI', codigoPostal2: '8401' },
    { localidad2: 'VILLA REGINA', codigoPostal2: '8336' },
    { localidad2: 'VILLA TURISMO', codigoPostal2: '8430' },
    { localidad2: 'YUQUINCHE', codigoPostal2: '8418' },
    { localidad2: 'ZANJON DE OYUELA', codigoPostal2: '8501' },

  ]

  updatePostalCode(event: any) {
    const selectedLocality = event.target.value;
    const selectedObject = this.localidades.find(item => item.localidad === selectedLocality);
    if (selectedObject) {
      this.formularioReclamo.patchValue({
        localidad: selectedObject.localidad, // si quieres mostrar el nombre de la localidad seleccionada en el campo de selección
        codigoPostal: selectedObject.codigoPostal
      });
    }
  }

  updatePostalCodeAlternativo(event:any){
    const selectedLocalidadAlternativa = event.target.value;
    const selectedObjectAlternativo = this.localidadesAlternativas2.find(item => item.localidad2 === selectedLocalidadAlternativa);
    if(selectedObjectAlternativo){
      this.formularioReclamo.patchValue({
        localidad2: selectedObjectAlternativo.localidad2,
        codigoPostal2: selectedObjectAlternativo.codigoPostal2
      });
    }
  }


  isChecked1:boolean = false;
  
  isChecked2: boolean = false;
  isChecked3:boolean = false;

  toggleEmailInput() {
    this.isChecked2 = !this.isChecked2;
  }
  togglecheckNombrePropioInput(){
    this.isChecked3 = !this.isChecked3;
  }


  ngOnInit(): void {
    this.formularioReclamo = this.fb.group({
      nombre: [''],
      apellido: [''],
      dni: [''],
      telefono: [''],

      checkNombrePropio:[false],
      nombreRepresentante:[''],
      apellidoRepresentante:[''],
      dniRepresentante:[''],

      direccion: [''],
      localidad: [''],
      codigoPostal: [''],
     
      direccionAlternativa: [''], 
      localidadAlternativa: [''],
      codigoPostalAlternativo: [''],

      // localidad2:[''],
      // codigoPostal2:[''],
      
      nis:[''],
      numeroDeCliente:[''],

      email: [''],
      errorFacturacion: [false],
      resarcimiento: [false],
      suspencionSuministro: [false],
      malaAtencionComercial: [false],
      negativaConexion: [false],
      inconvenienteTension: [false],
      descripcion: [''],
      emailNotifications: [false]

    });
  }

  
  //CHECKBOX DE COINCIDE CON DATOS 
  isChecked: boolean = false; 




  copiarLocalidad(event: any) {
    const localidadValue = this.formularioReclamo.get('localidad')?.value;
    if (event.target.checked && localidadValue) {
      this.formularioReclamo.get('localidadAlternativa')?.setValue(localidadValue);
    } else {
      this.formularioReclamo.get('localidadAlternativa')?.setValue('');
    }
  }
  copiarCodigoPostal() {
    const codigoPostalValue = this.formularioReclamo.get('codigoPostal')?.value;
    if (this.isChecked && codigoPostalValue) {
      this.formularioReclamo.get('codigoPostalAlternativo')?.setValue(codigoPostalValue);
    } else {
      this.formularioReclamo.get('codigoPostalAlternativo')?.setValue('');
    }
  }
  copiarDireccion(){
    const direccionValue = this.formularioReclamo.get('direccion')?.value;
    if(this.isChecked && direccionValue){
      this.formularioReclamo.get('direccionAlternativa')?.setValue(direccionValue);
    }else{
      this.formularioReclamo.get('direccionAlternativa')?.setValue('');
    }
  }





  onCheckboxChange(event: any) {
    this.isChecked = event.target.checked;
    this.copiarLocalidad(event);
    this.copiarCodigoPostal();
    this.copiarDireccion();
  }














  onsubmit() {
    for (let i = 0; i < this.files.length; i++) {
      if (this.files[i].size > this.maxSize) {
        this.errorMessage =
          'El tamaño del archivo excede el límite permitido de 10MB. No se puede enviar el formulario.';
        this.isButtonDisabled = true;
        return;
      }
    }

    const formData = new FormData();
    Object.keys(this.formularioReclamo.value).forEach((key) => {
      formData.append(key, this.formularioReclamo.value[key]);
    });

    this.files.forEach((file, index) => {
      formData.append('files', file, file.name);
    });

    this.emailService.sendEmailWithAttachment(formData).subscribe(
      (response) => {
        console.log('Correo electrónico enviado con éxito', response);
      },
      (error) => {
        console.error('Error al enviar el correo electrónico:', error);
      }
    );
  }









  onFileSelected(event: any) {
    const files: File[] = event.target.files;
    for (let i = 0; i < files.length; i++) {
      this.files.push(files[i]);
    }
  }









}
